config/routes.rb
Rails.application.routes.draw do
  devise_for :punters
  devise_for :users

  get "/" => "greetings#index"
end

app/models/punter.rb
class Punter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
    render(:index, locals: { user_description: user_description })
  end

  private

  def user_description
    user && [user.class, user.email].join(" ") || "Silly goose"
  end

  def user
    current_user || current_punter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/greetings/index.html.erb
<p>You are a type of <%= user_description %></p>

<br />
<br />
<br />
<br />

<% if user_signed_in? %>
  <p><%= link_to "User sign out", destroy_user_session_path %></p>
<% else %>
  <p><%= link_to "User sign up", new_user_registration_path %></p>
  <p><%= link_to "User sign in", new_user_session_path %></p>
<% end %>

<% if punter_signed_in? %>
  <p><%= link_to "Punter sign out", destroy_punter_session_path %></p>
<% else %>
  <p><%= link_to "Punter sign up", new_punter_registration_path %></p>
  <p><%= link_to "Punter sign in", new_punter_session_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authauthauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>